name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  release-docker:
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit

  release-galaxy:
    runs-on: ubuntu-latest  
    steps:
      - uses: ansible/ansible-publish-action@1.0.0
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
