name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  release-docker:
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit

  release-galaxy:
    runs-on: ubuntu-latest  
    #needs: [build]
    steps:
      - name: Download migrated collection artifacts
        uses: actions/download-artifact@v1
        with:
          name: collection
          path: .cache/collection-tarballs
      - name: Deploy Ansible collection to Galaxy
        run: ansible-galaxy collection publish .cache/collection-tarballs/*.tar.gz --api-key ${{ secrets.GALAXY_API_KEY }}

